@startuml
!include reqsrepo_json.puml
!include pumla_macros.puml

top to bottom direction

' show how a requirement with with full
' description is put onto a diagram
PUMLAPutReq(REQ_WS1)

' show how a requirement with a brief
' description is put onto a diagram
PUMLAPutReqBrief(REQ_WS2)

' enforcing layout
REQ_WS1 --[hidden]d> REQ_WS2

' try to put a req on the diagram
' but the alias is wrong
' ("-" instead of "_")
' causes a PUMLA Error Note
PUMLAPutReq(REQ-WS4)

@enduml
