@startuml
!include reqsrepo_json.puml
!include modelrepo_json.puml
!include pumla_macros.puml

!$PUMVarShowBodyInternals = %false()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowTaggedValues = %false()

allowmixing

PUMLAPutElement(tempSys)
PUMLAPutReqBrief(REQ_WS1)

tempSys <|-- REQ_WS1

@enduml
