@startuml
!include reqsrepo_json.puml
!include pumla_macros.puml

' show how the given requirement is broken down
' into further requirements with a
' "realizing" trace.
PUMLAPutReqsBreakdownTraceFor(REQ_WS1)


@enduml
