@startuml
!include reqsrepo_json.puml
!include pumla_macros.puml

' show how the given requirement is broken down
' into further requirements with a
' "realizing" trace.
PUMLAPutReqsBreakdownTraceFor(REQ_WS1)

'PUMLAPutReq(REQ_WS2)
'
'PUMLAPutReqBrief(REQ_WS3)
'
'' these arrows don't make sense, just to test
'REQ_WS2 --> REQ_WS3
'REQ_WS1 --> REQ_WS2

@enduml
