!$allelems = {"modelrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/WeatherStation", "modelrepofile": "./modelrepo_json.puml", "elements": [{"name": "Temperature System", "alias": "tempSys", "type": "node", "stereotypes": ["block"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./", "filename": "tempSys.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Arch Level", "values": ["0"]}]},
 {"name": "MyNewClass1", "alias": "MyNewClass1", "type": "class", "stereotypes": ["Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./", "filename": "reusableClass1.puml"},
 {"name": "tSys1 professional", "alias": "tSys1", "type": "node", "stereotypes": ["instance", "block"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "tempSys", "path": "./", "filename": "tempSysInstances.puml"},
 {"name": "tSys2", "alias": "tSys2", "type": "node", "stereotypes": ["instance", "block"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "tempSys", "path": "./", "filename": "tempSysInstances.puml"},
 {"name": "Temperature Sensor B", "alias": "tempSensorB", "type": "component", "stereotypes": ["block", "external System"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./tempSensorB/", "filename": "tempSensorB.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B1", "B2"]},
 {"tag": "Vendor", "values": ["B Inc."]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "Public State", "alias": "publicState", "type": "state", "stereotypes": [], "ports": [], "kind": "dynamic", "parent": "tempSensorB", "instclassalias": "-", "path": "./tempSensorB/", "filename": "publicState.puml"},
 {"name": "anotherClass", "alias": "anotherClass", "type": "class", "stereotypes": ["Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./anotherClass/", "filename": "anotherClass.puml"},
 {"name": "CWeather", "alias": "CWeather", "type": "class", "stereotypes": ["Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./CWeather/", "filename": "CWeather.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]}]},
 {"name": "w3", "alias": "w3", "type": "class", "stereotypes": ["instance", "Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "CWeather", "path": "./CWeather/", "filename": "FurtherWeatherInstances.puml"},
 {"name": "w4", "alias": "w4", "type": "class", "stereotypes": ["instance", "Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "CWeather", "path": "./CWeather/", "filename": "FurtherWeatherInstances.puml"},
 {"name": "Weather Data Instance 1", "alias": "w1", "type": "class", "stereotypes": ["instance", "Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "CWeather", "path": "./CWeather/", "filename": "WeatherInstances.puml"},
 {"name": "Weather Data Instance 2", "alias": "w2", "type": "class", "stereotypes": ["instance", "Python"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "CWeather", "path": "./CWeather/", "filename": "WeatherInstances.puml"},
 {"name": "Wireless Unit", "alias": "wirelessUnit", "type": "rectangle", "stereotypes": ["block", "external System"], "ports": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./wirelessUnit/", "filename": "wirelessUnit.puml", "taggedvalues": [{"tag": "Vendor", "values": ["XY"]},
 {"tag": "SecurityClass", "values": ["Alpha"]},
 {"tag": "Frequency Range", "values": ["5 GHz"]},
 {"tag": "Arch Level", "values": ["0"]}]},
 {"name": "Temperature Sensor A", "alias": "tempSensorA", "type": "component", "stereotypes": ["block"], "ports": [], "kind": "static", "parent": "tempSys", "instclassalias": "-", "path": "./tempSensorA/", "filename": "tempSensorA.puml", "taggedvalues": [{"tag": "Vendor", "values": ["A GmbH"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "**Internal Sequence**", "alias": "internalSequence", "type": "participant", "stereotypes": [], "ports": [], "kind": "dynamic", "parent": "tempSensorA", "instclassalias": "-", "path": "./tempSensorA/", "filename": "internalSequence.puml"},
 {"name": "Temperature Sensor B (dC)", "alias": "tempSensorBdC", "type": "component", "stereotypes": ["block"], "ports": [], "kind": "static", "parent": "tempSys", "instclassalias": "-", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "displayTemp", "alias": "displayTemp", "type": "component", "stereotypes": ["block"], "ports": [{"name": "tempDc", "interfacetype": "tempinterface", "type": "inout", "alias": "porttempdc", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Arch Level", "values": ["2"]},
 {"tag": "SysVariant", "values": ["B"]}]},
 {"name": "tempdF", "interfacetype": "tempinterface", "type": "in", "alias": "porttempdF", "taggedvalues": []}], "kind": "static", "parent": "tempSys", "instclassalias": "-", "path": "./displayTemp/", "filename": "displayTemp.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Brightness", "values": ["300 Nits"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "Temp. Converter", "alias": "tempConverter", "type": "component", "stereotypes": ["block"], "ports": [], "kind": "static", "parent": "tempSys", "instclassalias": "-", "path": "./tempConv/", "filename": "tempConverter.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Arch Level", "values": ["1"]}]}]}

!$allrelations = {"modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/WeatherStation", "modelrelationrepofile": "./modelrepo_json.puml", "relations": [{"id": "REL#tSys1tempSys", "start": "tSys1", "end": "tempSys", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./", "filename": "tempSysInstances.puml"},
 {"id": "REL#tSys2tempSys", "start": "tSys2", "end": "tempSys", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./", "filename": "tempSysInstances.puml"},
 {"id": "REL#publicStateToIF", "start": "publicState", "end": "temp_dF_tempSensorB", "reltype": "..>", "reltxt": "provides", "techntxt": "", "path": "./tempSensorB/", "filename": "tempSensorB.puml"},
 {"id": "REL#w3CWeather", "start": "w3", "end": "CWeather", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./CWeather/", "filename": "FurtherWeatherInstances.puml"},
 {"id": "REL#w4CWeather", "start": "w4", "end": "CWeather", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./CWeather/", "filename": "FurtherWeatherInstances.puml"},
 {"id": "REL#w1CWeather", "start": "w1", "end": "CWeather", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./CWeather/", "filename": "WeatherInstances.puml"},
 {"id": "REL#w2CWeather", "start": "w2", "end": "CWeather", "reltype": "..>", "reltxt": "instance of", "techntxt": "", "path": "./CWeather/", "filename": "WeatherInstances.puml"},
 {"id": "tempSensorBdCRel#1", "start": "tempSensorBdC", "end": "tempSensorB", "reltype": "..>", "reltxt": "use", "techntxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B2"]}]},
 {"id": "tempSensorBdCRel#2", "start": "tempSensorBdC", "end": "tempConverter", "reltype": "..>", "reltxt": "use", "techntxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B2"]}]},
 {"id": "tempSensorBdCRel#3", "start": "tempSensorBdC", "end": "tempSensorB", "reltype": "..>", "reltxt": "useForB3", "techntxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B3"]}]},
 {"id": "tempSensorBdCRel#4", "start": "tempSensorBdC", "end": "tempConverter", "reltype": "..>", "reltxt": "useForB3", "techntxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B3"]}]}]}

!$allconnections = {"modelconnectionrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/WeatherStation", "modelconnectionrepofile": "./modelrepo_json.puml", "connections": [{"id": "CON#_SYS_VAR_B", "start": "temp_dC_tempSensorBdC", "end": "temp_dC_displayTemp", "contype": "--", "contxt": "", "path": "./connections/", "filename": "connections_tempSys_Var_B.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B1", "B2"]}]},
 {"id": "CON#_SYS_VAR_A", "start": "temp_dC_tempSensorA", "end": "temp_dC_displayTemp", "contype": "--", "contxt": "", "path": "./connections/", "filename": "connections_tempSys_Var_A.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["A"]}]},
 {"id": "CON#_SYS_VAR_B2", "start": "temp_dC_tempSensorBdC", "end": "temp_dC_displayTemp", "contype": "--", "contxt": "", "path": "./connections/", "filename": "connections_tempSys_Var_B2.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["B2"]}]},
 {"id": "C#2", "start": "temp_dC_tempConverter", "end": "temp_dC_tempSensorBdC", "contype": "--", "contxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"},
 {"id": "C#3", "start": "temp_dF_tempSensorB", "end": "temp_dF_tempConverter", "contype": "--", "contxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"}]}

