@startuml
!include reqsrepo_json.puml

!alias = "REQ_WS1"

!foreach $r in $allreqs.reqs
!if $r.alias == alias
object $r.alias {
|= //attribute// |= //content//|
|= Type | $r.type |
|= Content | $r.content |
|= Status  | $r.status |
}
!endif
!if $r.derived_from == alias
object $r.alias {
|= //attribute// |= //content//|
|= Type | $r.type |
|= Content | $r.content |
|= Status  | $r.status |
}
!endif
!endfor

!foreach $r in $allreqs.reqs
!if $r.derived_from !=null
$r.derived_from  <|-- $r.alias
!endif
!endfor


@enduml
