@startuml
!include <c4/C4_Container.puml>
!include pumla_macros.puml

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")

'AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())

PUMLAC4Person(user, "Customer", "People that need products")
PUMLAC4Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
PUMLAC4Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
PUMLAC4Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
PUMLAC4Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
PUMLAC4ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")
PUMLAC4Container(archive, "Archive", "Audit logging", "Stores 5 years", $tags="backup")


PUMLAC4Rel("id1", user, spa, "Uses", "https")
PUMLAC4Rel("id2", spa, api, "Uses", "https")
PUMLAC4Rel_R("id3", api, db, "Reads/Writes")
PUMLAC4Rel("id4",admin, spaAdmin, "Uses", "https")
PUMLAC4Rel("id5", spaAdmin, api, "Uses", "https")
PUMLAC4Rel_L("id6", api, archive, "Writes", "messages", $tags="backup")

user .. spa : huhu

SHOW_LEGEND()
@enduml
