@startuml
!include reqsrepo_json.puml

!alias = "REQ_WS1"

!foreach $r in $allreqs.reqs
!if $r.alias == alias
object $r.alias {
|= Type | $r.type |
|= Content | $r.content |
|= Status  | $r.status |
}
!endif
!if $r.derived_from == alias
object $r.alias {
|= Type | $r.type |
|= Content | $r.content |
|= Status  | $r.status |
}
$r.derived_from  <|-- $r.alias
!endif
!endfor

!$cnt = $cnt + 1
!$cnt = $cnt + 1
$cnt

@enduml
