@startuml

!startsub showInterfaces
temp_dF )--> displayTemp
temp_dC )--> displayTemp
!endsub

!startsub showBody
component displayTemp <<block>>  {

[display]
[conversion]

}
!endsub

!startsub showDescription
note bottom of displayTemp
    Gets as input a temperature in
    degree Celsius or Fahrenheit, or both.
    Displays both temperature values.
    Calls the tempConverter for conversion if
    only one value is given as input.
end note
!endsub

@enduml