'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../../../pumla_macros.puml

!if ($PUMVarShowBody)
component displayTemp <<block>>  {
    !if ($PUMVarShowBodyInternals)
    [display]
    [conversion]
    !endif
}
!endif

PUMLAPutInterface("temp_dC", temp_dC_displayTemp, displayTemp, "in")

!if ($PUMVarShowDescr)
note bottom of displayTemp
    Gets as input a temperature in
    degree Celsius or Fahrenheit, or both.
    Displays both temperature values.
    Calls the tempConverter for conversion if
    only one value is given as input.
end note
!endif

@enduml