'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../pumla_macros.puml
!include ./../modelrepo_json.puml

PUMLAReUsableAsset("displayTemp", displayTemp, component, "<<block>>") {

    PUMLARUAPutTaggedValues()

    !if ($PUMVarShowBodyInternals)
    PUMLARUAInternals() {
        component display
        component conversion
    }
    !endif
}


PUMLAAddTaggedValue(displayTemp, "Vendor", "C Ltd.")
PUMLAAddTaggedValue(displayTemp, "Brightness", "300 Nits")

PUMLAInterface("temp_dC", temp_dC_displayTemp, displayTemp, "in")

PUMLAInterface("temp_dF", temp_dF_displayTemp, displayTemp, "in")

!if ($PUMVarShowDescr)
note bottom of displayTemp
    Gets as input a temperature in
    degree Celsius or Fahrenheit, or both.
    Displays both temperature values.
    Calls the tempConverter for conversion if
    only one value is given as input.
end note
!endif

@enduml