@startuml
!$allelems = {"elements": [{"name": "Temperature System", "parent": "-", "filename": "tempSys.puml", "alias": "tempSys", "path": "./test/examples/", "type": "-"},
 {"name": "Temperature Sensor B", "parent": "-", "filename": "tempSensorB.puml", "alias": "tempSensorB", "path": "./test/examples/tempSensorB/", "type": "-"},
 {"name": "Wireless Unit", "parent": "-", "filename": "wirelessUnit.puml", "alias": "wirelessUnit", "path": "./test/examples/wirelessUnit/", "type": "-"},
 {"name": "Temperature Sensor A", "parent": "tempSys", "filename": "tempSensorA.puml", "alias": "tempSensorA", "path": "./test/examples/tempSensorA/", "type": "-"},
 {"name": "Temperature Sensor B (dC)", "parent": "tempSys", "filename": "tempSensorBdC.puml", "alias": "tempSensorBdC", "path": "./test/examples/tempSensorBdC/", "type": "-"},
 {"name": "displayTemp", "parent": "tempSys", "filename": "displayTemp.puml", "alias": "displayTemp", "path": "./test/examples/displayTemp/", "type": "-"},
 {"name": "Temp. Converter", "parent": "tempSys", "filename": "tempConverter.puml", "alias": "tempConverter", "path": "./test/examples/tempConv/", "type": "-"},
 {"name": "block", "parent": "", "filename": "block.puml", "alias": "block", "path": "./templates/sysml/", "type": "-"},
 {"name": "atomic_element", "parent": "-", "filename": "atomic_element.puml", "alias": "atomic_element", "path": "./templates/generic/", "type": "-"},
 {"name": "atomic_element_with_comments", "parent": "-", "filename": "atomic_element_with_comments.puml", "alias": "atomic_element_with_comments", "path": "./templates/generic/", "type": "-"}]}
@enduml
