'DISCLAIMER: this part is highly inspired by the
'            properties handling of the C4 model
'            extension for PlantUML from here:
'            https://github.com/plantuml-stdlib/C4-PlantUML
'
'The original code in 'C4.puml' is licensed under this:
'
'MIT License
'
'Copyright (c) 2018 Ricardo Niepel
'
'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:
'
'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.
'
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.

' Element tags
' ##################################

!global $tvTable = ""
!global $tvTableCaption = ""
!global $tvColCaption = "="

' kept preparation for up to 4 columns
!unquoted function SetTaggedValuesHeader($col1Name, $col2Name, $col3Name = "", $col4Name = "")
  !$tvColCaption = ""
  !$tvTableCaption = "|= <size: 10>" + $col1Name + " |= <size: 10>" + $col2Name + " |"
  !if ($col3Name != "")
    !$tvTableCaption = $tvTableCaption + "= " + $col3Name + " |"
  !endif
  !if ($col4Name != "")
    !$tvTableCaption = $tvTableCaption + "= " + $col4Name + " |"
  !endif
  !return ""
!endfunction

!unquoted function WithoutTaggedValuesHeader()
  !$tvTableCaption = ""
  !$tvColCaption = "="
  !return ""
!endfunction

' add a tag/value pair to the table
!unquoted function AddTaggedValue($col1, $col2, $col3 = "", $col4 = "")
  !if ($propTable == "")
    !if ($propTableCaption != "")
      !$tvTable = $tvTableCaption + "\n"
    !endif
  !else
    !$tvTable = $tvTable + "\n"
  !endif
  !$tvTable = $tvTable + "| <size: 8>" + $col1 + " |" + $tvColCaption + " <size: 8>" + $col2 + " |"
  !if ($col3 != "")
    !tvTable = $tvTable + " " + $col3 + " |"
  !endif
  !if ($col4 != "")
    !$tvTable = $tvTable + " " + $col4 + " |"
  !endif
  !return ""
!endfunction

' this returns the text for the tagged value table.
' works only in quoted areas, not where real linebreaks
' are expected like in "note as xy [lines with line breaks...] end note".
!unquoted function PUMLAPutTagTable()
  !if ($propTable != "")
    !$retTable = "\n" + $tvTableCaption + $tvTable
    !tvTable = ""
    !return $retTable
  !endif
  !return ""
!endfunction

' set standard property header for tagged values
SetTaggedValuesHeader("Tag","Value")

' put the tagged value table into a rectangle.
' so it is not necessarily exactly below the name
' of the surrounding element.
!unquoted procedure PUMLAPutTaggedValues()
!if ($PUMVarShowTaggedValues)
rectangle "Tagged Values PUMLAPutTagTable()" {
}
!endif
!endprocedure

