
!unquoted procedure PUMLAErrorCheck($suc, $elemalias, $errortxt, $reasontxt, $hinttxt)
!if ($PUMVarShowPUMLAErrorNotes)
!if %not($suc=="1")
!$notename = "pum_error_note_nr" + %string($pum_global_error_cnt)
note as $notename #red
**<i>PUMLA Error:**
'Running Nr.$pum_global_error_cnt
$errortxt: $elemalias

**Reason:**
$reasontxt

**Hint:**
$hinttxt

end note
!$tempval = $pum_global_error_cnt
%set_variable_value("$pum_global_error_cnt", $tempval + 1)
!endif
!endif
!end procedure

!unquoted procedure PUMLAPutElementErrorCheck($suc, $elemalias)
PUMLAErrorCheck($suc, $elemalias, "Could not put element with alias", "Element was not found in model repo.", "- try to update the model repo, or %newline()- check the alias for misspellings.")
!end procedure

!unquoted procedure PUMLACreateInstanceError($elemalias)
PUMLAErrorCheck("0", $elemalias, "Could not create instance of element with alias", "The element that should be instantiated %newline()was not found in the model repo.", "- try to update the model repo, or %newline()- check the alias for misspellings.")
!end procedure

' --------------------------------------------
' put an element referenced by path and filename
' by including its file
'
!unquoted function _PUMElement($folderpath,$filename)
!$retval = "!include " + $allelems.modelrepopath + "/" + %substr($folderpath,2) + $filename
!return $retval
!endfunction

' --------------------------------------------
' put an element referenced by path and filename
' by including its file
'
!unquoted procedure _PUMPutElement($folderpath,$filename)
!include $allelems.modelrepopath/%substr($folderpath,2)/$filename
!endprocedure

' --------------------------------------------
' put an element referenced by path and filename
' by including its file using Filters
'
!unquoted procedure _PUMPutElementFiltered($folderpath,$filename)
!if ((_PUMLACheckFilterOutShowElement($el)) && (_PUMLACheckFilterInShowElement($el)))
    !include $allelems.modelrepopath/%substr($folderpath,2)/$filename
!endif
!endprocedure

' ############################################
' ---------------------------------------------
' check filter type conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterOutElementTypeShow($elem)
!local $internal_retval = %false()
!if ($pum_global_element_filter_out_type != "")
    !if ($elem.type == $pum_global_element_filter_out_type)
        !$internal_retval = %true()
    !endif
!endif
!return $internal_retval
!endfunction

' ############################################
' ---------------------------------------------
' check filter stereotype conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterOutElementStereotypeShow($elem)
!local $internal_retval = %false()
!if ($pum_global_element_filter_out_stereotype != "")
    !foreach $st in $elem.stereotypes
    !if ($st == $pum_global_element_filter_out_stereotype)
        !$internal_retval = %true()
    !endif
    !endfor
!endif
!return $internal_retval
!endfunction


' ############################################
' ---------------------------------------------
' check filter tag/value conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterOutElementTagValueShow($elem)
!local $internal_retval = %false()
!if ($pum_global_element_filter_out_tv_tag != "")
    !foreach $tagvalue in $elem.taggedvalues
        !if ($tagvalue.tag == $pum_global_element_filter_out_tv_tag)
            !if ($pum_global_element_filter_out_tv_value == "")
                !$internal_retval = %true()
            !else
                !foreach $tvv in $tagvalue.values
                    !if ($tvv == $pum_global_element_filter_out_tv_value)
                        !$internal_retval = %true()
                    !endif
                !endfor
            !endif
        !endif
    !endfor
!endif
!return $internal_retval
!endfunction

' ############################################
' ---------------------------------------------
' check filter conditions for the given element.
' return false if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterOutShowElement($elem)
!local $internal_retval = %true()

!if ((_PUMLACheckFilterOutElementTypeShow($elem)) || (_PUMLACheckFilterOutElementStereotypeShow($elem)) || (_PUMLACheckFilterOutElementTagValueShow($elem)))
    !$internal_retval = %false()
!endif

!return $internal_retval
!endfunction

' ############################################
' ---------------------------------------------
' check filter type conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterInElementTypeShow($elem)
!local $internal_retval = %false()
!if ($pum_global_element_filter_in_type != "")
    !if ($elem.type != $pum_global_element_filter_in_type)
        !$internal_retval = %true()
    !endif
!endif
!return $internal_retval
!endfunction

' ############################################
' ---------------------------------------------
' check filter stereotype conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterInElementStereotypeShow($elem)
!local $internal_retval = %true()
!if ($pum_global_element_filter_in_stereotype != "")
    !foreach $st in $elem.stereotypes
    !if ($st == $pum_global_element_filter_in_stereotype)
        !$internal_retval = %false()
    !endif
    !endfor
!else
    !$internal_retval = %false()
!endif
!return $internal_retval
!endfunction


' ############################################
' ---------------------------------------------
' check filter tag/value conditions for the given element.
' return true if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterInElementTagValueShow($elem)
!local $internal_retval = %true()
!if ($pum_global_element_filter_in_tv_tag != "")
    !foreach $tagvalue in $elem.taggedvalues
        !if ($tagvalue.tag == $pum_global_element_filter_in_tv_tag)
            !if ($pum_global_element_filter_in_tv_value == "")
                !$internal_retval = %false()
            !else
                !foreach $tvv in $tagvalue.values
                    !if ($tvv == $pum_global_element_filter_in_tv_value)
                        !$internal_retval = %false()
                    !endif
                !endfor
            !endif
        !endif
    !endfor
!else
    !$internal_retval = %false()
!endif
!return $internal_retval
!endfunction




' ############################################
' ---------------------------------------------
' check filter conditions for the given element.
' return false if the element shall not be
' shown but filtered out.
'
!unquoted function _PUMLACheckFilterInShowElement($elem)
!local $internal_retval = %true()

!if ((_PUMLACheckFilterInElementTypeShow($elem)) || (_PUMLACheckFilterInElementStereotypeShow($elem)) || (_PUMLACheckFilterInElementTagValueShow($elem)))
    !$internal_retval = %false()
!endif


'!if ($pum_global_element_filter_in_type != "")
'    !if ($elem.type != $pum_global_element_filter_in_type)
'        !$internal_retval = %false()
'    !endif
'!endif
!return $internal_retval
!endfunction

!unquoted function _PUMIsStatic($elemalias)
!$retval = %true()
!foreach $el in $allelems.elements
    !if ($el.alias == $elemalias)
        !if ($el.kind == "dynamic")
            !$retval = %false()
        !endif
    !endif
!endfor
!return $retval
!endfunction



' ############################################
' ---------------------------------------------
' create an instance of an element that exists
' in the json model repo. Internal txt creation.
!unquoted function _PUMLACreateInstanceOf($elemalias, $instalias, $instname)
!$retval = "ERROR"
!foreach $el in $allelems.elements
    !if ($el.alias == $elemalias)
        !if ($PUMVarShowInstantiationRel)
            !$iname = $instname
        !else
            !$iname = $instname + " (" + $el.name + ")"
        !endif
        $elt = "ERROR - no valid type"
        !if (($el.type  == "-") || ($el.type  == ""))
            !$elt = "rectangle"
        !else
            !$elt = $el.type
        !endif
        !$sts = ""
        !foreach $st in $el.stereotypes
            !$sts = $sts + " <<" + $st + ">>"
        !endfor
        !$retval = $elt + ' "' + $iname + '" as ' + $instalias + ' <<instance>> ' + $sts
    !endif
!endfor
!return $retval
!endfunction


' ############################################
' ---------------------------------------------
' default footer with pumla git repo reference.
' can be overwritten or turned off with the
' global variable.
!if ($PUMVarShowPUMLAFooterNote)
center footer created with help of **pumla**: https://github.com/DrMarkusVoss/pumla
!endif


' ############################################
' ---------------------------------------------
' add a tagged value to to element referenced by its alias
!unquoted procedure PUMLATestNewTVs($elemalias)
!$notestr = "-"
!foreach $el in $allelems.elements
    !if ($el.alias == $elemalias)
        !foreach $tv in $el.taggedvalues
            !$notestr = $notestr + " \n" + "tag=" + $tv.tag + "; values = " + $tv.values
        !endfor
        note as n987
            $notestr
        end note
    !endif
!endfor
!endprocedure


