!$PUMVarShowDescr = %false()
!$PUMVarShowInterfaces = %false()

' --------------------------------------------
' get an element referenced by Coding Rule
'
!unquoted procedure PUMPutElement($compname)
!include $compname/$compname.puml
!endprocedure
' ---------------------------------------------

' ############################################
' --------------------------------------------
' get an element referenced by path and filename name
'
!unquoted procedure _PUMPutElement($filename, $folderpath)
!include $folderpath/$filename
!endprocedure
' ---------------------------------------------

' ############################################

' ---------------------------------------------
' get an element referenced by JSON puml file
'
!unquoted procedure PUMJPutElement($alias, $description="", $label="", $technology="", $size=12, $colour="green")

!foreach $emp in allelems.elements
!if ($emp.name == $alias)
 !$alias = $emp.salary
!endif
!endfor

rectangle $alias as "
<color:$colour><<$alias>></color>
==$label==
//<size:$size>[$technology]</size>//

  $description"
!endprocedure
' --------------------------------------------
