' put the tagged value table with data
' from modelrepository
!unquoted procedure _TaggedValuesTable($elalias)
|= Tag |= Values |
!foreach $el in $allelems.elements
    !if ($el.alias == $elalias)
        !foreach $tv in $el.taggedvalues
            !$lmax = 0
            !foreach $t in $tv.values
                !$lmax = $lmax + 1
            !endfor
            !$l = 0
            !$tvs = ""
            !foreach $t in $tv.values
                !$tvs = $tvs + $t
                !$l = $l + 1
                !if ($l < $lmax)
                    !$tvs = $tvs + ", "
                !endif
            !endfor
| $tv.tag | $tvs |
        !endfor
    !endif
  !endfor
!endprocedure

' put the tagged value table for ports with data
' from modelrepository
!unquoted procedure _TaggedValuesTableForPorts($elalias)
|= Tag |= Values |
!foreach $el in $allelems.elements
    !if ($el.alias == $pum_global_current_rua_alias)
        !foreach $p in $el.ports
            !if ($p.alias == $elalias)
                !foreach $tv in $p.taggedvalues
                    !$lmax = 0
                    !foreach $t in $tv.values
                        !$lmax = $lmax + 1
                    !endfor
                    !$l = 0
                    !$tvs = ""
                    !foreach $t in $tv.values
                        !$tvs = $tvs + $t
                        !$l = $l + 1
                        !if ($l < $lmax)
                            !$tvs = $tvs + ", "
                        !endif
                    !endfor
| $tv.tag | $tvs |
                !endfor
            !endif
        !endfor
    !endif
  !endfor
!endprocedure

' put the tagged value table into a note
' to be included in a non-class element
!unquoted procedure PUMLAPutTaggedValues($elalias)
!if ($PUMVarShowTaggedValues)
!$nn = "NN_" + $elalias + "_TV"
!global $pum_global_current_rua_tvnote = $nn
note as $nn #$PUMColorTaggedValues
_TaggedValuesTable($elalias)
end note
!endif
!endprocedure

' put the tagged value table into a note
' to be included in a non-class element
' for use within a re-usable element definition.
!unquoted procedure PUMLARUAPutTaggedValues()
PUMLAPutTaggedValues($pum_global_current_rua_alias)
!endprocedure

' put the tagged value table as note to a class
!unquoted procedure PUMLARUAPutTaggedValuesAsNoteToElement()
!if ($PUMVarShowTaggedValues)
!$nn = "NN_" + $pum_global_current_rua_alias + "_TV"
!global $pum_global_current_rua_tvnote = $nn
note $PUMTaggedValuesNoteToElementAlignment of $pum_global_current_rua_alias #$PUMColorTaggedValues
_TaggedValuesTable($pum_global_current_rua_alias)
end note
!endif
!endprocedure

' put the tagged value table as note to a class
!unquoted procedure PUMLAPutTaggedValuesAsNoteToElement($elalias)
!if ($PUMVarShowTaggedValues)
!$nn = "NN_" + $elalias + "_TV"
note $PUMTaggedValuesNoteToElementAlignment of $elalias #$PUMColorTaggedValues
_TaggedValuesTable($elalias)
end note
!endif
!endprocedure


' put the tagged value table as note to a port
!unquoted procedure PUMLAPutTaggedValuesAsNoteToPort($elalias)
!if ($PUMVarShowTaggedValues)
!if ($PUMVarShowInterfaces)
!if %not(_PUMLACheckFilterOutPortTagValueShow($pum_global_current_rua_alias, $elalias))
!$nn = "NN_" + $elalias + "_TV"
note $PUMTaggedValuesNoteToElementAlignment of $elalias #$PUMColorTaggedValues
_TaggedValuesTableForPorts($elalias)
end note
!endif
!endif
!endif
!endprocedure