'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../pumla_macros.puml
!include ./../modelrepo_json.puml

PUMLAReUsableAsset("displayTemp", displayTemp, component, "<<block>>") {

    PUMLARUAPort("tempDc", "tempinterface", porttempdc) #orange

    PUMLARUAPort("tempdF", "tempinterface", porttempdF) #lightblue

    PUMLARUAPutTaggedValues()

    PUMLARUAInternals() {
        component display
        component conversion
    }
}


PUMLAAddTaggedValue(displayTemp, "Vendor", "C Ltd.")
PUMLAAddTaggedValue(displayTemp, "Brightness", "300 Nits")
PUMLAAddTaggedValue(displayTemp, "Arch Level", "1")
PUMLAAddTaggedValue(porttempdc, "Vendor", "C Ltd.")
PUMLAPutTaggedValuesAsNoteToElement(porttempdc)


PUMLATypedInterface("temp_dC", "hello", temp_dC_displayTemp, displayTemp, "in")

PUMLAInterface("temp_dF", temp_dF_displayTemp, displayTemp, "in")

!if ($PUMVarShowDescr)
note bottom of displayTemp
    Gets as input a temperature in
    degree Celsius or Fahrenheit, or both.
    Displays both temperature values.
    Calls the tempConverter for conversion if
    only one value is given as input.
end note
!endif
PUMLAReUsableAssetFinalize()
@enduml