'PUMLADR
@startuml
!include pumla_macros.puml
!include modelrepo_json.puml

!$PUMVarShowBodyInternals = %false()

'left to right direction
'PUMLADL direction: l-to-r

'skinparam linetype ortho

title Pumla Layout example: Temperature System elements

PUMLAPutElement(tempSensor)

PUMLAPutElement(tempProcessing)

PUMLAPutElement(displayTemp)

' connecting the top level elements
tempSensor_temp_dK_raw -> tempProcessing_temp_dK_raw_in
tempProcessing_temp_dC_filtered_out -> temp_dC_displayTemp

@enduml