!$allelems = {"modelrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/simple/ports", "modelrepofile": "./modelrepo_json.puml", "elements": [{"name": "Temperature Processing", "alias": "tempProcessing", "type": "component", "stereotypes": ["block"], "ports": [{"name": "temp_dK_raw", "interfacetype": "", "type": "in", "alias": "tempProcessing_temp_dK_raw_in", "taggedvalues": []},
 {"name": "temp_dC_filtered", "interfacetype": "", "type": "out", "alias": "tempProcessing_temp_dC_filtered_out", "taggedvalues": []}], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./processing/", "filename": "tempProcessing.puml", "taggedvalues": [{"tag": "Vendor", "values": ["B GmbH"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "Temperature Sensor", "alias": "tempSensor", "type": "component", "stereotypes": ["block"], "ports": [{"name": "temp_dK_raw", "interfacetype": "", "type": "out", "alias": "tempSensor_temp_dK_raw", "taggedvalues": []}], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./sensor/", "filename": "tempSensor.puml", "taggedvalues": [{"tag": "Vendor", "values": ["B GmbH"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "displayTemp", "alias": "displayTemp", "type": "component", "stereotypes": ["block"], "ports": [{"name": "temp_dC", "interfacetype": "", "type": "inout", "alias": "temp_dC_displayTemp", "taggedvalues": []},
 {"name": "temp_dF", "interfacetype": "", "type": "in", "alias": "temp_dF_displayTemp", "taggedvalues": []},
 {"name": "tempdF", "interfacetype": "tempinterface", "type": "in", "alias": "porttempdF", "taggedvalues": []}], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./display/", "filename": "displayTemp.puml", "taggedvalues": [{"tag": "Vendor", "values": ["C Ltd."]},
 {"tag": "Brightness", "values": ["300 Nits"]},
 {"tag": "Arch Level", "values": ["1"]}]}]}

!$allrelations = {"modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/simple/ports", "modelrelationrepofile": "./modelrepo_json.puml", "relations": []}

!$allconnections = {"modelconnectionrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/simple/ports", "modelconnectionrepofile": "./modelrepo_json.puml", "connections": []}

