'PUMLAMR
@startuml
!include pumla_macros.puml
!include modelrepo_json.puml

!$PUMVarShowBodyInternals = %true()

'left to right direction

'skinparam linetype ortho

Title Overview Temperature System

PUMLACheatSheetAllAttributes()

PUMLAPutElement(tempSensor)

PUMLAPutElement(tempProcessing)

PUMLAPutElement(displayTemp)

tempSensor_temp_dK_raw -> tempProcessing_temp_dK_raw_in
tempProcessing_temp_dC_filtered_out -> temp_dC_displayTemp

@enduml