'PUMLAMR
@startuml

!if ($PUMVarShowInterfaces)
temp_dC <-- comp_TC
temp_dF )--> comp_TC
!endif

!if ($PUMVarShowBody)
component "tempConverter" <<block>> as comp_TC {
!if ($PUMVarShowBodyInternals)
[conversionModule]
[formulaLib]
!endif
}
!endif

!if ($PUMVarShowDescr)
note bottom of comp_TC
    Perform a conversion from
    degree Fahrenheit to degree
    Celsius.
end note
!endif

@enduml