'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../../../pumla_macros.puml
!include ./../../../pumla_tagged_values.puml
!include ./../modelrepo_json.puml

!if ($PUMVarShowBody)
component "Temp. Converter" <<block>>  as tempConverter {

    PUMLAPutTaggedValues(tempConverter)

    !if ($PUMVarShowBodyInternals)
    [conversionModule]
    [formulaLib]
    !endif
}
!endif

PUMLAAddTaggedValue(tempConverter, "Vendor", "C Ltd.")

PUMLAInterface("temp_dC", temp_dC_tempConverter, tempConverter, "out")
PUMLAInterface("temp_dF", temp_dF_tempConverter, tempConverter, "in")

!if ($PUMVarShowDescr)
note bottom of tempConverter
    Perform a conversion from
    degree Fahrenheit to degree
    Celsius.
end note
!endif

@enduml