'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../pumla_macros.puml
!include ./../modelrepo_json.puml

PUMLAReUsableAsset("Temp. Converter", tempConverter, component, "<<block>>") {

    PUMLARUAPutTaggedValues()

    PUMLARUAInternals() {
        component conversionModule
        component formulaLib
    }
}


PUMLARUAAddTaggedValue("Vendor", "C Ltd.")

PUMLARUAInterface("temp_dC", temp_dC_tempConverter, "out")
PUMLARUAInterface("temp_dF", temp_dF_tempConverter, "in")

note as ndescr_tempConverter
    Perform a conversion from
    degree Fahrenheit to degree
    Celsius.
end note

PUMLARUADescr(ndescr_tempConverter)

PUMLAReUsableAssetFinalize()
@enduml