!$allelems = {"modelrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/thisShallBeIgnored/C4example", "modelrepofile": "./modelrepo_json.puml", "elements": [{"name": "Web Application", "alias": "web_app", "type": "C4Container", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./web_app/", "filename": "web_app.puml"},
 {"name": "Administration User", "alias": "administrationUser", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "administrationUser.puml"},
 {"name": "Anonymous User", "alias": "anonymousUser", "type": "C4Person_Ext", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "anonymousUser.puml"},
 {"name": "Aggregated User", "alias": "aggregatedUser", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "aggregatedUser.puml"},
 {"name": "Remote Control", "alias": "remoteControl", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./remoteControl/", "filename": "remoteControl.puml", "taggedvalues": [{"tag": "Vendor", "values": ["D GmbH"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "techtribes.js", "alias": "techtribes", "type": "C4System_Boundary", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./techtribes.js/", "filename": "techtribes.puml"},
 {"name": "Relational Database", "alias": "rel_db", "type": "C4ContainerDb", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./rel_db/", "filename": "rel_db.puml"}]}

!$allrelations = {"modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/thisShallBeIgnored/C4example", "modelrelationrepofile": "./modelrepo_json.puml", "relations": []}

!$allconnections = {"modelconnectionrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/thisShallBeIgnored/C4example", "modelconnectionrepofile": "./modelrepo_json.puml", "connections": []}

