'PUMLAMR
@startuml

'!include ./../displayTemp/displayTemp.puml
'!include ./../tempSensorBdC/tempSensorBdC.puml
'
'!if ($PUMVarShowInterfaces)
'temp_dC_tempSensorBdC--temp_dC_displayTemp
'!endif
PUMLAConnection(temp_dC_tempSensorBdC, "--", temp_dC_displayTemp, "", "CON#99")

@enduml