'PUMLARR
@startuml

!include ./../displayTemp/displayTemp.puml
!include ./../tempSensorB/tempSensorB.puml
!include ./../tempConv/tempConverter.puml

!if ($PUMVarShowInterfaces)
temp_dF_tempSensorB--temp_dF_tempConverter
temp_dC_tempConverter--temp_dC_displayTemp
!endif

@enduml