!$allelems = {"modelrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/C4example", "modelrepofile": "./modelrepo_json.puml", "elements": [{"name": "Web Application", "alias": "web_app", "type": "C4Container", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./web_app/", "filename": "web_app.puml"},
 {"name": "Blogs", "alias": "blogs", "type": "C4System_Ext", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./ext_systems/", "filename": "blogs.puml"},
 {"name": "Twitter", "alias": "twitter", "type": "C4System_Ext", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./ext_systems/", "filename": "twitter.puml"},
 {"name": "GitHub", "alias": "github", "type": "C4System_Ext", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./ext_systems/", "filename": "github.puml"},
 {"name": "Updater", "alias": "updater", "type": "C4Container", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./updater/", "filename": "updater.puml"},
 {"name": "File System", "alias": "filesystem", "type": "C4Container", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./filesystem/", "filename": "filesystem.puml"},
 {"name": "Administration User", "alias": "administrationUser", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "administrationUser.puml"},
 {"name": "Anonymous User", "alias": "anonymousUser", "type": "C4Person_Ext", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "anonymousUser.puml"},
 {"name": "Aggregated User", "alias": "aggregatedUser", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./users/", "filename": "aggregatedUser.puml"},
 {"name": "Remote Control", "alias": "remoteControl", "type": "C4Person", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./remoteControl/", "filename": "remoteControl.puml", "taggedvalues": [{"tag": "Vendor", "values": ["D GmbH"]},
 {"tag": "Arch Level", "values": ["1"]}]},
 {"name": "NoSQL Data Store", "alias": "nosql", "type": "C4ContainerDb", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./nosql/", "filename": "nosql.puml"},
 {"name": "techtribes.js", "alias": "techtribes", "type": "C4System_Boundary", "stereotypes": [], "kind": "static", "parent": "-", "instclassalias": "-", "path": "./techtribes.js/", "filename": "techtribes.puml"},
 {"name": "Relational Database", "alias": "rel_db", "type": "C4ContainerDb", "stereotypes": [], "kind": "static", "parent": "techtribes", "instclassalias": "-", "path": "./rel_db/", "filename": "rel_db.puml"}]}

!$allrelations = {"modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/C4example", "modelrelationrepofile": "./modelrepo_json.puml", "relations": [{"id": "overall_users_rel1", "start": "anonymousUser", "end": "web_app", "reltype": "C4BiRel", "reltxt": "Uses", "techntxt": "HTTPS", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "overall_users_rel2", "start": "aggregatedUser", "end": "web_app", "reltype": "C4Rel", "reltxt": "Uses", "techntxt": "HTTPS", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "overall_users_rel3", "start": "administrationUser", "end": "web_app", "reltype": "C4Rel", "reltxt": "Uses", "techntxt": "HTTPS", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "overall_extsys_rel1", "start": "updater", "end": "twitter", "reltype": "C4Rel", "reltxt": "Gets profile information and tweets from", "techntxt": "HTTPS", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "overall_extsys_rel2", "start": "updater", "end": "github", "reltype": "C4Rel", "reltxt": "Gets information about public code repositories from", "techntxt": "HTTPS", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "overall_extsys_rel3", "start": "updater", "end": "blogs", "reltype": "C4Rel", "reltxt": "Gets content using RSS and Atom feeds from", "techntxt": "HTTP", "path": "./", "filename": "relations_overall_system.puml"},
 {"id": "updater_rel1", "start": "updater", "end": "rel_db", "reltype": "C4Rel_U", "reltxt": "Reads from and writes data to", "techntxt": "SQL/JDBC, port 3306", "path": "./techtribes.js/", "filename": "relations_updater.puml"},
 {"id": "updater_rel2", "start": "updater", "end": "filesystem", "reltype": "C4Rel_U", "reltxt": "Writes to", "techntxt": "", "path": "./techtribes.js/", "filename": "relations_updater.puml"},
 {"id": "updater_rel3", "start": "updater", "end": "nosql", "reltype": "C4Rel_U", "reltxt": "Reads from and writes to", "techntxt": "MongoDB wire protocol, port 27017", "path": "./techtribes.js/", "filename": "relations_updater.puml"},
 {"id": "webapp_rel1", "start": "web_app", "end": "rel_db", "reltype": "C4Rel", "reltxt": "Reads from and writes to", "techntxt": "SQL/JDBC, port 3306", "path": "./techtribes.js/", "filename": "relations_web_app.puml"},
 {"id": "webapp_rel2", "start": "web_app", "end": "filesystem", "reltype": "C4Rel", "reltxt": "Reads from", "techntxt": "", "path": "./techtribes.js/", "filename": "relations_web_app.puml"},
 {"id": "webapp_rel3", "start": "web_app", "end": "nosql", "reltype": "C4Rel", "reltxt": "Reads from", "techntxt": "MongoDB wire protocol, port 27017", "path": "./techtribes.js/", "filename": "relations_web_app.puml", "taggedvalues": [{"tag": "SysVariant", "values": ["A"]}]}]}

!$allconnections = {"modelconnectionrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples/C4example", "modelconnectionrepofile": "./modelrepo_json.puml", "connections": []}

