@startuml
!include pumla_macros.puml
!include modelrepo_json.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

' add the users to the diagram
PUMLAPutElement(anonymousUser)
PUMLAPutElement(administrationUser)
PUMLAPutElement(aggregatedUser)

' add the "system", "techtribes.js":
' that one includes everything within
' the "techtribes" system boundary.
PUMLAPutElement(techtribes)

' add the external systems to the diagram
PUMLAPutElement(twitter)
PUMLAPutElement(blogs)
PUMLAPutElement(github)

' add all relations to the diagram
PUMLAPutAllRelations()

' final layout adoption
Lay_R(rel_db, filesystem)
@enduml
