@startuml
!include pumla_macros.puml
!include modelrepo_json.puml
LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

' add the users to the diagram
PUMLAPutElement(anonymousUser)
PUMLAPutElement(administrationUser)
PUMLAPutElement(aggregatedUser)

' add the "system", "techtribes.js":
' that one includes everything within
' the "techtribes" system boundary.
PUMLAPutElement(techtribes)

PUMLAPutElement(twitter)
PUMLAPutElement(blogs)
PUMLAPutElement(github)

PUMLAPutAllRelations()

PUMLACheatSheetAllAttributes()

Lay_R(rel_db, filesystem)

@enduml
