'PUMLAMR
@startuml

PUMLAC4BiRel("overall_users_rel1", anonymousUser, web_app, "Uses", "HTTPS")
PUMLAC4Rel("overall_users_rel2", aggregatedUser, web_app, "Uses", "HTTPS")
PUMLAC4Rel("overall_users_rel3", administrationUser, web_app, "Uses", "HTTPS")

PUMLAC4Rel("overall_extsys_rel1", updater, twitter, "Gets profile information and tweets from", "HTTPS")
PUMLAC4Rel("overall_extsys_rel2", updater, github, "Gets information about public code repositories from", "HTTPS")
PUMLAC4Rel("overall_extsys_rel3", updater, blogs, "Gets content using RSS and Atom feeds from", "HTTP")


@enduml