'PUMLAMR
'PUMLAPARENT: -

@startuml
!include ./../../pumla_macros.puml
!include ./../../pumla_tagged_values.puml

PUMLAReUsableAsset("Element Name", element_alias, component, "<<block>>") {

PUMLARUAPutTaggedValues()

PUMLARUAInternals() {

    [internal element]
    [another internal element]
    PUMLAPutElement(tempSensorB)

    PUMLAInjectChildElements(element_alias)
}

    PUMLAPutInternalElement(tempSensorA)
}

PUMLARUAAddTaggedValue("Vendor", "XY")
PUMLARUAAddTaggedValue("SecurityClass", "Alpha")
PUMLARUAAddTaggedValue("Frequency Range", "5 GHz")

PUMLARUAInterface("some_interface", some_interface_element_alias, "in")

note as n7987473
    Re-usable element description.
end note

PUMLARUADescr(n7987473)

PUMLAReUsableAssetFinalize()
@enduml
