'PUMLAMR
'PUMLAPARENT: -
@startuml
!include ./../../pumla_macros.puml
!include ./../../pumla_tagged_values.puml

rectangle "Element Name" <<block>> as element_alias {
    PUMLAPutTaggedValues()

    !if ($PUMVarShowBodyInternals)
        component display
        component conversion
        PUMLAInjectChildElements(element_alias)
    !endif

    PUMLAPutInternalElement(tempSensorA)
}

PUMLAAddTaggedValue(element_alias, "Vendor", "XY")
PUMLAAddTaggedValue(element_alias, "SecurityClass", "Alpha")
PUMLAAddTaggedValue(element_alias, "Frequency Range", "5 GHz")

' the interface alias should be <interface_name>_<modelelement_alias>
PUMLAInterface("some_interface", some_interface_element_alias, element_alias, "in")

!if ($PUMVarShowDescr)
    note bottom of element_alias
        Description of the re-usable element.
    end note
!endif

@enduml
