'PUMLAMR
'PUMLAPARENT: -
@startuml
!include ./../../pumla_macros.puml
!include ./../../pumla_tagged_values.puml

!if ($PUMVarShowTaggedValues)
    AddTaggedValue("Vendor", "XY")
    AddTaggedValue("SecurityClass", "Alpha")
    AddTaggedValue("Frequency Range", "5 GHz")
!endif

!if ($PUMVarShowBody)
    rectangle "Temp. Display" <<block>> as displayTemp {
        PUMLAPutTaggedValues()
        !if ($PUMVarShowBodyInternals)
            [display]
            [conversion]
            PUMLAInjectChildElements( displayTemp )
        !endif
    }
!endif

!if ($PUMVarShowInterfaces)
    ' the interface alias should be <interface_name>_<modelelement_alias>_
    interface temp_dC as temp_dC_displayTemp
    temp_dC_displayTemp )--> displayTemp
!endif

!if ($PUMVarShowDescr)
    note bottom of displayTemp
        Gets as input a temperature in
        degree Celsius or Fahrenheit, or both.
    end note
!endif

@enduml