'PUMLAMR
@startuml

'                   start            type      end                 label             alias
PUMLAConnection(temp_dC_tempSensorA, "--", temp_dC_displayTemp,   "hard-wired",    "CON#_SYS_VAR_A")

@enduml