'PUMLAMR
@startuml
!include ./../pumla_macros.puml
!include ./../modelrepo_json.puml

!startsub BODY
PUMLAFullyInstantiatableClass(CWeather, "<<Python>>")
{
        ' private functions and members
        ' are considered internal
        !if ($PUMVarShowBodyInternals)
            -m_tempCurrent_dC : int
            -m_airPressureCurrent_bar : int
            -m_tempHistory_dC : int[7]
        !else
            .. <i>private internals hidden ..
            --
        !endif
        ' public methods are not internal
        +getTemperature_dC() : int
        +getAirPressure_bar() : int
        +setTemperature_dC(temp_dC : int) : void
        +setAirPressure_bar(ap_bar : int) : void
        +lastSevenDayTemperatureAvg_dC() : int

}
!endsub

PUMLARUAAddTaggedValue("Vendor", "C Ltd.")

PUMLAPutTaggedValuesAsNoteToElement(CWeather)

note as ndescr_CWeather
    A class managing weather data.
end note

PUMLARUADescr(ndescr_CWeather)

PUMLAReUsableAssetFinalize()

@enduml