@startuml
' the following file gets generated when you call
' "pumla update" in this directory
!include modelrepo_json.puml
!include pumla_macros.puml
!include ./../../../templates/sysml/skin.puml

!$PUMVarShowBodyInternals = %false()
!$PUMVarShowBodyInternalsDyn = %false()
!$PUMVarShowTaggedValues = %true()

title Example using an Element Filter

' this is standard PlantUML.
' Choosing a nice scheme and
' adopting the background color.
!$BGCOLOR=LightGrey
!theme sketchy-outline

' this is PUMLA-specific, the color of tagged value
' notes
!$PUMColorTaggedValues = darkgreen

note as note1
The element type filter for this diagram is set to "node"
and the element stereotype filter is set to "external System".
That is why on this diagram only "Temperature Sensor B (dC)"
and "Temp. Converter" appear. All other elements that are put
on are filtered out.

Also using the "sketchy-outline" theme here, therefore adopted
the backgroundcolor for the tagged values note to darkgreen.
end note

' without this line the interfaces of the component
' would be displayed as classes. the following
' command enforces this diagram to be a component
' diagram where we have these circles as interfaces.
PUMLASetAsComponentDiagram()

' sets the element filter out for this diagram to "node".
' that is why on this diagram only "Temp. Converter"
' and "Temperature Sensor B (dC)"
' appears, as it is of type "component". All other elements that
' are put on are filtered out, because they are "node"s.
'PUMLASetElementFilterOutType("component")
PUMLASetElementFilterOutType("node")
'PUMLASetElementFilterInType("node")

'PUMLASetElementFilterInTagValue("SysVariant", "")
'PUMLASetElementFilterOutTag("SysVariant")

'PUMLASetElementFilterInType("node")

PUMLASetElementFilterOutStereotype("external System")
' put the following elements on the diagram:

' type = "component"
' stereotype = "block", "external System"
PUMLAPutElement(tempSensorB)

' type = "component"
' stereotype = "block"
PUMLAPutElement(tempConverter)

' type = "node"
' stereotype = "block"
PUMLAPutElement(tempSys)

' type = "component"
' stereotype = "block"
PUMLAPutElement(tempSensorBdC)

@enduml
