@startuml
!include modelrepo_json.puml
!include pumla_macros.puml
!include ./../../../templates/sysml/skin.puml

!$PUMVarShowDescr = %true()
!$PUMVarShowInterfaces = %true()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()
!$PUMVarShowBodyInternalsDyn = %false()
!$PUMVarShowTaggedValues = %true()

scale 0.8

title Element injection example

' only element "tempSys" is put on the diagram,
' but internals are shown.
' if you look at the definition of the "tempSys"
' model element, you do not see the internals
' defined. they are injected via the
' "PUMLAInjectChildElements" macro. this tells
' pumla to insert into this element all other
' elements that call "tempSys" their parent in
' the second line of the .puml file.
' that way, the parent element definition does
' not need to be changed when another child has
' been created. the children themselves are
' designed for usage in the parent context, so
' they should not be used without their parent.
PUMLAPutElement(tempSys)

PUMLAPutConnectionsForElement(tempConverter)

@enduml