'PUMLAMR
@startuml
!include ./../../../pumla_macros.puml

PUMLAReUsableClass("anotherClass", "<<Python>>")
{
        ' private functions and members
        ' are considered internal
        !if ($PUMVarShowBodyInternals)
            -my_private_membervar : int
        !else
            .. <i>private internals hidden ..
--
        !endif
        ' public methods are not internal
        +my_public_getMethod() : int
}

note as ndescr_anotherClass
    Another class for the examples.
end note

PUMLARUADescr(ndescr_anotherClass)

PUMLAReUsableAssetFinalize()
@enduml