@startuml
!include ./../modelrepo_json.puml
!include ./../pumla_macros.puml

title Overview of all Cheat Sheets to show the contents of the model repo of **pumla**

PUMLACheatSheetAllAttributes()
PUMLARelCheatSheetAllAttributes()
PUMLAConCheatSheetAllAttributes()

@enduml