@startuml
!include ./../modelrepo_json.puml
!include ./../pumla_macros.puml
!include ./../templates/sysml/skin.puml

!$PUMVarShowInterfaces = %false()

title Overview of all elements and their relations of the model repo of **pumla**

'put all elements of json-repo onto the diagram
PUMLAPutAllElements()

'put all relations of json-repo onto the diagram
PUMLAPutAllRelations()

@enduml