' alias = "HelloMyFriend"
' expected_result = ("hello my friend", "component", ["block", "weird"])
@startuml

component "hello my friend" <<block>> <<weird>> as HelloMyFriend

note as n1
    this is some note
    regarding MyFriend.
end note

rectangle "huhu this is my testName" <<block>> <<component>><<external System>> as hu


@enduml