' glob_alias = "otherAbstractClass"
' glob_expected_result = ("otherAbstractClass", "abstract class", ["C++"])
'PUMLAMR
@startuml
'!include ./../../../pumla_macros.puml

!if ($PUMVarShowBody)
    abstract class otherAbstractClass <<C++>>

!endif

!if ($PUMVarShowDescr)
    note bottom of otherAbstractClass
        An abstract class test example.
    end note
!endif

@enduml