'PUMLAMR
@startuml
'!include ./../../../pumla_macros.puml

!if ($PUMVarShowBody)
    class "CWeather" as CWeather <<Python>>  {

        ' private functions and members
        ' are considered internal
        !if ($PUMVarShowBodyInternals)
            -m_tempCurrent_dC : int
            -m_airPressureCurrent_bar : int
            -m_tempHistory_dC : int[7]
        !endif
        ' public methods are not internal
        +getTemperature_dC() : int
        +getAirPressure_bar() : int
        +setTemperature_dC(temp_dC : int) : void
        +setAirPressure_bar(ap_bar : int) : void
        +lastSevenDayTemperatureAvg_dC() : int

    }
!endif

!if ($PUMVarShowDescr)
    note bottom of CWeather
        A class managing weather data.
    end note
!endif

@enduml