'PUMLAMR
'PUMLAINSTANCES
@startuml
!include ./../../../pumla_macros.puml
!include ./../modelrepo_json.puml

' here 2 re-usable instances of CWeather are defined.
' see line 2, where we mark this as instance file.
' other re-usable element files shall only contain
' one model element (atomic definition). but for
' instances that might be annoying, so we make an
' exception to allow for multiple instance element
' definitions in one file.

PUMLAFullInstanceOf("CWeather", "w3")
PUMLAFullInstanceOf("CWeather", "w4")

note left of w4
    w3 and w4 are instances created with the
    "PUMLAFullInstanceOf" macro. That way, the
    instances were automatically equipped with
    the methods of the parent class.
end note

@enduml
