'PUMLAMR
'PUMLAINSTANCES
@startuml
!include ./../../../pumla_macros.puml
!include ./../modelrepo_json.puml

' here 2 re-usable instances of CWeather are defined.
' see line 2, where we mark this as instance file.
' other re-usable element files shall only contain
' one model element (atomic definition). but for
' instances that might be annoying, so we make an
' exception to allow for multiple instance element
' definitions in one file.

PUMLAFullInstanceOf("CWeather", "w3")
PUMLAFullInstanceOf("CWeather", "w4")

note left of w4
 an additional note to
 instance w4.
end note

@enduml
