@startuml

!startsub showBlock
'add block definition with internals here, e.g.:
'component "displayTemp" <<block>> as comp_DisplayTemp {
'
'[display]
'[conversion]
'}

!endsub

!startsub showInterfaces
'add interface connections here
' e.g.: temp_dC )--> comp_DisplayTemp

!endsub

!startsub showDescription
'add description note to the block here, e.g.
'note bottom of comp_DisplayTemp
'    Gets as input a temperature in
'    degree Celsius or Fahrenheit, or both.
'end note

!endsub

@enduml