''PUMLAMR
''PUMLAPARENT:
@startuml
'!include pumpla.puml

' if you want to add tagged values,
' just uncomment the following lines
' and adopt the tags and values:
'!if ($PUMVarShowTaggedValues)
'AddProperty("Vendor", "XY")
'AddProperty("SecurityClass", "Alpha")
'AddProperty("Frequency Range", "5 GHz")
'!endif

!if ($PUMVarShowBody)
'add block definition with internals here, e.g.:
'component "displayTemp" <<block>> as comp_DisplayTemp {

'if the element has tagged values defined above, just uncomment
'the following line:
'PUMLAPutTaggedValues()

!if ($PUMVarShowBodyInternals)
' add some internal elements here, if the block is
' "non-aggregating", meaning all of its description
' must be put into this file, like this:
'[display]
'[conversion]

' if the block is "aggregating", meaning others
' can add internals without changing this definition
' then, the following line must be inserted/uncommented
' (the name in the brackets must of course be adapted
'  to the name of the real component/block)
'PUMLAInjectChildElements(comp_DisplayTemp)
!endif
'}
!endif

!if ($PUMVarShowInterfaces)
'add interface connections here
' e.g.: temp_dC )--> comp_DisplayTemp

!endif

!if ($PUMVarShowDescr)
'add description note to the block here, e.g.
'note bottom of comp_DisplayTemp
'    Gets as input a temperature in
'    degree Celsius or Fahrenheit, or both.
'end note

!endif

@enduml