@startuml
skinparam rectangle {
    backgroundColor<<external System>> LightGrey
    backgroundColor<<instance>> LightYellow
    roundCorner<<block>> 15
}
skinparam component {
    backgroundColor<<external System>> LightGrey
    backgroundColor<<instance>> LightYellow
    roundCorner<<block>> 15
}
skinparam node {
    backgroundColor<<instance>> LightYellow
}
@enduml
