'PUMLAMR
@startuml
!include ./../pumla_macros.puml
!include ./../modelrepo_json.puml

!if ($PUMVarShowBody)
'add block definition with internals here, e.g.:
component "Temperature Sensor B" <<block>> <<external System>> as tempSensorB {
    ' this puts the table with the tagged values here
    ' to show.
    ' even without the following macro, tagged values
    ' attached with "PUMLAAddTV" will still be in the
    ' model repo attached to the element, they will just
    ' not be seen on diagrams, even if the global variable
    ' for showing them is set to true.
    ' You will be able to see the full list of available
    ' tagged values and the elements they are attached to
    ' with an upcoming CheatSheet macro.
    PUMLAPutTaggedValues(tempSensorB)

    !if ($PUMVarShowBodyInternals)
        component "unknown elements"
    !endif

    PUMLAPutInternalDynElement(publicState)
}
!endif

' This macro adds a tag/value pair to the element
' with the given alias.
PUMLAAddTaggedValue(tempSensorB, "SysVariant", "B1")
PUMLAAddTaggedValue(tempSensorB, "SysVariant", "B2")
PUMLAAddTaggedValue(tempSensorB, "Vendor", "B Inc.")

PUMLAInterface("temp_dF", temp_dF_tempSensorB, tempSensorB, "out")
PUMLARelation(publicState, "..>", temp_dF_tempSensorB, "provides", "REL#publicStateToIF")
'publicState ..> temp_dF_tempSensorB : provides
'PUMLAPutRelation("REL#publicStateToIF")

!if ($PUMVarShowDescr)
note bottom of tempSensorB
    Temperature Sensor of company B.
    Provides the temperature in degree
    Fahrenheit.
end note

!endif
@enduml