'PUMLAMR
@startuml
!include ./../../../pumla_macros.puml
!include ./../../../pumla_tagged_values_mr.puml
!include ./../modelrepo_json.puml

!if ($PUMVarShowBody)
'add block definition with internals here, e.g.:
component "Temperature Sensor B" <<block>> <<external System>> as tempSensorB {
    PUMLAPutTaggedValues(tempSensorB)
    !if ($PUMVarShowBodyInternals)
    [unknown elements]
    !endif

    PUMLAPutInternalDynElement(publicState)
}
!endif

' PUMLAAddTV is a macro under development.
' in pumla v0.5 this functionality is
' subsequently under development. For v0.6
' it will be introduced officially, but the
' API will change.
PUMLAAddTV(tempSensorB, "SysVariant", "B1")
PUMLAAddTV(tempSensorB, "SysVariant", "B2")
PUMLAAddTV(tempSensorB, "Vendor", "B")

PUMLAPutInterface("temp_dF", temp_dF_tempSensorB, tempSensorB, "out")
PUMLARelation(publicState, "..>", temp_dF_tempSensorB, "provides", "REL#publicStateToIF")
'publicState ..> temp_dF_tempSensorB : provides
'PUMLAPutRelation("REL#publicStateToIF")

!if ($PUMVarShowDescr)
note bottom of tempSensorB
    Temperature Sensor of company B.
    Provides the temperature in degree
    Fahrenheit.
end note

!endif
@enduml