'PUMLAMR
@startuml
!include ./../../../pumla_macros.puml
!if ($PUMVarShowBody)
'add block definition with internals here, e.g.:
component "Temperature Sensor B" <<block>> <<external System>> as tempSensorB {
    !if ($PUMVarShowBodyInternals)
    [unknown internals]
    !endif
}
!endif

PUMLAPutInterface("temp_dF", temp_dF_tempSensorB, tempSensorB, "out")

!if ($PUMVarShowDescr)
note bottom of tempSensorB
    Temperature Sensor of company B.
    Provides the temperatur in degree
    Fahrenheit.
end note

!endif
@enduml