@startuml

skinparam componentStyle uml2

title pumla Simple Context Diagram


:Developer: as dev


rectangle "pumla.py" <<application>> as pumla {
}

rectangle "pumla_macros.puml" <<PlantUML Extension>> as pmac {
}

rectangle "PlantUML" <<application>> as plantuml {
}

note top of pmac
    Extension of PlantUML.
    Macros to make re-use of
    the model elements within
    the JSON model repository.
end note

rectangle "project git-repo" <<source code>> as pgr {
rectangle "puml-files" <<arch>>  as pumlf {
}
rectangle "pumla model repo file" <<arch>> as pumlamr {
}

rectangle "Programming Language \nCodeSource Code files" {
}
rectangle "Build Tool Configuration" as btc {
}
}

note top of pumla
    Scans for and parses PUMLA
    marked PlantUML files, creates a
    model-repository JSON file accessible
    by PlantUML.
end note


node "Some Computer" as sco {
cloud "Java SE RTE" as Java {
}
 note left of Java : version >= 10.14.6

cloud Python {
 }
 note left of Python: version >= 3.8.2

cloud PlantUML as puml {

 }
 note left of puml: version >= 1.2021.x

}

cloud "Some Cloud" as cloud {
 rectangle "CI/CT environment" as cict {
 }
}

Java -[hidden]-> Python
Python -[hidden]-> puml

pumla --> sco: runs on

dev-->pumla: create & maintain architecture
dev-->pgr: work on
pumla ..> btc: integrate into
pumla ..> pumlamr: generate
pumla ..> pumlf: find and enlist
pumlf ..> pumlamr: include
pumlf ..> pmac : include
dev --> pmac : use
dev --> pumlf : create and maintain
pgr --> cict : gets build and tested completely in
pgr --> sco : gets build and tested reduced locally
pumlf --> plantuml: use to create diagrams
@enduml