@startuml

skinparam componentStyle uml2

title pumla Simple Context Diagram


:Developer: as dev


rectangle "pumla.py" <<application>> as pumla {
}

rectangle "pumla_macros.puml" <<PlantUML Extension>> as pmac {
}

rectangle "PlantUML" <<application>> as plantuml {
}

note top of pmac
    Extension of PlantUML.
    Macros to make re-use of
    the model elements within
    the JSON model repository.
end note

rectangle "project git-repo" <<source code>> as pgr {
rectangle "PUMLA Model Element description" <<PlantUML *.puml>>  as pumlf {
}
rectangle "Architecture Diagrams \ndescribing \nSource Code Solution" <<PlantUML *.puml>>  as archdiags {
}
rectangle "pumla model repo file" <<JSON PlantUML file>> as pumlamr {
}

rectangle "Programming Language \nCodeSource Code files" {
}
rectangle "Build Tool Configuration" as btc {
}
}

rectangle "Modelling Guideline" <<markdown document>> as modguid {
}

rectangle "Model Element templates" <<PlantUML  template>> as templ {
}

note top of pumla
    Scans for and parses PUMLA
    marked PlantUML files, creates a
    model-repository JSON file accessible
    by PlantUML.
end note


node "Some Computer" as sco {
cloud "Java SE RTE" as Java {
}
 note left of Java : version >= 10.14.6

cloud Python {
 }
 note left of Python: version >= 3.8.2

cloud PlantUML as puml {

 }
 note left of puml: version >= 1.2021.x

}

cloud "Some Cloud" as cloud {
 rectangle "CI/CT environment" as cict {
 }
}

Java -[hidden]-> Python
Python -[hidden]-> puml
pumlamr -[hidden]-> sco
pumlamr -[hidden]-> cloud

pumla --> sco: runs on

dev-->pumla: use
dev-->pgr: work on
dev-->modguid: follow
dev-->templ : use
dev --> archdiags : model architecture\nusing model repo
templ-->pmac :use
modguid--> pmac: proposes usage of
modguid--> templ: proposes usage of
archdiags-->pmac : include
archdiags-->pumlamr : include
pumla ..> btc: integrate into
pumla ..> pumlamr: generate/update
pumla ..> pumlf: find and enlist
pumlf ..> pumlamr: include
pumlf ..> pmac : include
dev --> pmac : use
dev --> pumlf : create and maintain
pgr --> cict : gets build and tested completely in
pgr --> sco : gets build and tested reduced locally
pumlf --> plantuml: use to create diagrams
archdiags -->plantuml: use to create diagrams
@enduml