@startuml
' the following file gets generated when you call
' "python pumla.py update" in this directory
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowBodyInternals = %false()
!$PUMVarShowBodyInternalsDyn = %false()
!$PUMVarShowInstantiationRel = %false()

title Advanced Filter Example

PUMLASetAsComponentDiagram()

note as note1
First we set the filter-in to tag/value "Vendor"/""C Ltd."
and then put all elements of stereotype "block" onto the
diagram. That leads to the 4 elements that have both,
stereotype "block" and the above tag/value combination.

After that, we change the filter-in to tag/value
"Vendor"/"B Inc." and again put all elements of
stereotype "block" onto the diagram. With that filter-in
we get another element onto the diagram, "Temperature
Sensor B".
end note


PUMLASetElementFilterInTagValue("Vendor", "C Ltd.")

PUMLAPutAllElementsOfStereotype("block")

' it is possible to change the filter within a
' diagram description. The filter is only
' applied to the following lines and overwrites
' the preceeding filter values of the same type.
PUMLASetElementFilterInTagValue("Vendor", "B Inc.")

PUMLAPutAllElementsOfStereotype("block")

@enduml
