@startuml
'tempConv/tempConverter
!includesub tempConv/tempConverter.puml!showBlock
!includesub tempConv/tempConverter.puml!showDescription

'displayTemp/displayTemp.puml
!includesub displayTemp/displayTemp.puml!showBlock
!includesub displayTemp/displayTemp.puml!showDescription
@enduml