@startuml
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowDescr = %true()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()
!$PUMVarShowTaggedValues = %true()

title Overview all components

'put all elements of json-repo onto the diagram
PUMLAPutAllElements()

note bottom of displayTemp
    this is an additional note to
    the imported displayTemp
end note
@enduml
