
@startuml
!include repo_json.puml
'!include all_components_generated.puml
!include ./../../pumla.puml


!$PUMVarShowDescr = %true()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()

'!include tempSys.puml

title Overview all components


PUMJPutElement(trara, "This description is %newline()on several lines", $size=10, $technology="Java")

'PUMLAPutElement(displayTemp)
PUMLAPutElement(tempSys)
'PUMLAPutElement(displayTemp)

note bottom of displayTemp
this is a note to the imported displayTemp
end note

@enduml
