@startuml
' the following file gets generated when you call
' "python pumla.py update" in this directory
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowBodyInternals = %true()
!$PUMVarShowBodyInternalsDyn = %true()

title Cheat Sheet with all attributes example

' this commands gives you an overview
' on the contents of the model repository
' with all the available attributes. you
' can use it to keep the overview of the
' details and manage your architectural
' artefacts.
PUMLACheatSheetAllAttributes()

' ahh... now I know that the element I need
' has the alias "wirelessUnit"...
' I put it on the diagram and then I can
' comment out the cheat sheet.
'PUMLAPutElement(wirelessUnit)

PUMLAPutElement(tempSensorB)

@enduml