@startuml
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowDescr = %true()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()
!$PUMVarShowTaggedValues = %true()
!$PUMVarShowInstantiationRel = %false()
!$PUMVarShowImplicitRels = %true()

title All Classes from Model Repository

' if you want to mix classes and other elements
' on a diagram you need to do this:
allowmixing

' put all classes onto this diagram
' which becomes a class diagram with that
PUMLAPutAllClasses()

' if you want to show the internals
' and mix with other non-class elements,
' you need to allow mixing in order not
' to get an error (this is a PlantUML approach,
' not pumla). Still, elements like "[some comp]"
' will lead to a PlantUML error, therefore
' you can only interact with re-usable elements
' that include such definitions in their internals
' by blending out the internals first.
!$PUMVarShowBodyInternals = %false()
PUMLAPutElement(tempSys)
!$PUMVarShowBodyInternals = %true()

tempSys .. CWeather : somehow related

@enduml
