@startuml
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml
!include ./../../pumla_tagged_values.puml

!$PUMVarShowDescr = %true()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()

'title Overview on all model elements in repository

'put all elements of json-repo onto the diagram
PUMLAPutAllElements()

@enduml