@startuml

!include modelrepo_json.puml
!include pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowDescr = %false()
!$PUMVarShowInterfaces = %true()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()
!$PUMVarShowBodyInternalsDyn = %false()
!$PUMVarShowTaggedValues = %true()
!$PUMVarShowImplicitRels = %false()
!$PUMVarShowConnections = %true()

title Overview Temperature System Variant B and Connection selection

' put the elements of interest onto the diagrams
' by naming them by their alias.
' Not sure what elements you want and what their
' alias is? Use the "PUMLACheatSheet" command...
PUMLAPutElement(tempSys)
PUMLAPutElement(tempSensorBdC)
PUMLAPutElement(wirelessUnit)

' here are different variants of how the overall
' system is connected. Uncomment the one you
' like to see. Adopt the removal of not used
' or unwanted elements at the bottom of the file.

'PUMLAPutConnection("CON#_SYS_VAR_A")

PUMLAPutConnection("CON#_SYS_VAR_B")
PUMLAPutConnection("C#2")
PUMLAPutConnection("C#3")

'PUMLAPutConnection("CON#_SYS_VAR_B2")
internet_tempSys -- internet_wirelessUnit

PUMLAConCheatSheetAllAttributes()

' remove the elements you do not want to see.
' the following are included as internal parts
' of the "tempSys". But in Variant B/B2 they are
' not connected and therefore not needed.
' You can remove them by their alias.
remove tempSensorA
remove temp_dC_tempSensorA

@enduml