@startuml

!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml


!$PUMVarShowDescr = %false()
' by default the global variables are "true",
' so the following lines could also be removed.
' they are just there so that you can toggle them
' and try out the effect it has.
!$PUMVarShowInterfaces = %true()
!$PUMVarShowBody = %true()
!$PUMVarShowBodyInternals = %true()
!$PUMVarShowTaggedValues = %true()
!$PUMVarShowImplicitRels = %false()

title Overview on all model elements in repository

'put all elements of json-modelrepo onto the diagram
PUMLAPutAllElementsMix()

'!include ./relations/relations_tempSys_Var_A.puml
'!include ./relations/relations_tempSys_Var_B.puml
!include ./relations/relations_tempSys_Var_B2.puml

internet_tempSys -- internet_wirelessUnit

@enduml