@startuml
' the following file gets generated when you call
' "pumla update" in this directory
!include modelrepo_json.puml
!include pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowBodyInternals = %true()
!$PUMVarShowBodyInternalsDyn = %true()

title Another example with an element having dynamic behaviour inside

PUMLAPutElement(tempSensorA)

@enduml
