@startuml
' the following file gets generated when you call
' "pumla update" in this directory
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!include ./../../templates/sysml/skin.puml

!$PUMVarShowBodyInternals = %true()
!$PUMVarShowBodyInternalsDyn = %true()

title Example on how to re-use an existing state machine

' put the re-usable element "publicState" onto the diagram
PUMLAPutElement(publicState)

' additions to the existing diagram, that reference
' the internal states like "State2" from the
' "publicState" state diagram definition

' 3 new states:
state "Exception Handler" as newState #red {
}
state "Exception cleared" as newState2 #orange {
}
state "Wait for manual\nrestart by user" as newState3 #green {
}

' connect the "newState" with the "State2" from the
' model repository (inside "publicState):
State2 --> newState : Exception #1
newState --> newState2 : clearance
newState2 --> newState3 : trigger restart procedure
' connect again to "State1" of the
' "publicState" state machine
newState3 --> State1 : restart

@enduml
