@startuml
' the following 2 files gets generated when you call
' "python pumla.py update" in this directory
!include modelrepo_json.puml
!include relationsrepo_json.puml
!include ./../../pumla_macros.puml
' this template skin colors instances for some
' types in LightYellow
!include ./../../templates/sysml/skin.puml

!$PUMVarShowDescr = %false()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBodyInternals = %false()
!$PUMVarShowBody = %true()

' this following flag allows to show/not show the automatically
' created relation between the instance and its "class"
!$PUMVarShowInstantiationRel = %true()
!$PUMVarShowImplicitRels = %true()

title Example showing explicit relations of the model repository



PUMLAPutElement(tempSensorBdC)
PUMLAPutElement(tempSensorB)
PUMLAPutElement(tempConverter)

'PUMLAPutRelation("tempSensorBdCRel#1")
'PUMLAPutRelation("tempSensorBdCRel#2")

PUMLAPutRelationsForElement(tempSensorBdC)
'PUMLAPutRelationsForElement(tempSensorB)

PUMLARelCheatSheetAllAttributes()

'remove tempConverter

@enduml