@startuml
' the following file gets generated when you call
' "python pumla.py update" in this directory
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
' this template skin colors instances for some
' types in LightYellow
!include ./../../templates/sysml/skin.puml

!$PUMVarShowDescr = %false()
!$PUMVarShowInterfaces = %false()
!$PUMVarShowBodyInternals = %false()

' this following flag allows to show/not show the automatically
' created relation between the instance and its "class"
!$PUMVarShowInstantiationRel = %true()

title Example for creating an instance of an \n element from the model repository

' create the instance "ts1" of model element with alias "tempSys".
' the name contains whitespaces, therefore name and alias are
' not equal and this version of the macro is called.
PUMLACreateInstanceOf(tempSys, ts1, "ts1 professional")

' create another instance "ts2" from same model element.
' the instance name equals the alias, therefore is not
' allowed to contain whitespaces.
PUMLACreateInstanceOf(tempSys, ts2)

' the instance inherits the stereotypes of the
' model element it is derived from.
PUMLACreateInstanceOf(wirelessUnit, wu1)

note left of ts1
    you can attach notes
    to the instance or use
    it in any other way by
    referring to the alias.
end note

ts1 <..> ts2 : some interaction

@enduml
