!$allelems = {"modelrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples", "modelrepofile": "./modelrepo_json.puml", "elements": [{"name": "Temperature System", "alias": "tempSys", "type": "node", "stereotypes": [], "parent": "-", "instclassalias": "-", "path": "./", "filename": "tempSys.puml"},
 {"name": "tSys1 professional", "alias": "tSys1", "type": "-", "stereotypes": ["instance"], "parent": "-", "instclassalias": "tempSys", "path": "./", "filename": "tempSysInstances.puml"},
 {"name": "tSys2", "alias": "tSys2", "type": "-", "stereotypes": ["instance"], "parent": "-", "instclassalias": "tempSys", "path": "./", "filename": "tempSysInstances.puml"},
 {"name": "Temperature Sensor B", "alias": "tempSensorB", "type": "component", "stereotypes": ["block", "external System"], "parent": "-", "instclassalias": "-", "path": "./tempSensorB/", "filename": "tempSensorB.puml"},
 {"name": "Wireless Unit", "alias": "wirelessUnit", "type": "rectangle", "stereotypes": ["block", "external System"], "parent": "-", "instclassalias": "-", "path": "./wirelessUnit/", "filename": "wirelessUnit.puml"},
 {"name": "Temperature Sensor A", "alias": "tempSensorA", "type": "component", "stereotypes": ["block"], "parent": "tempSys", "instclassalias": "-", "path": "./tempSensorA/", "filename": "tempSensorA.puml"},
 {"name": "Temperature Sensor B (dC)", "alias": "tempSensorBdC", "type": "component", "stereotypes": ["block"], "parent": "tempSys", "instclassalias": "-", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"},
 {"name": "displayTemp", "alias": "displayTemp", "type": "component", "stereotypes": ["block"], "parent": "tempSys", "instclassalias": "-", "path": "./displayTemp/", "filename": "displayTemp.puml"},
 {"name": "Temp. Converter", "alias": "tempConverter", "type": "component", "stereotypes": ["block"], "parent": "tempSys", "instclassalias": "-", "path": "./tempConv/", "filename": "tempConverter.puml"}]}

!$allrelations = {"modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples", "modelrelationrepofile": "./modelrepo_json.puml", "relations": [{"id": "REL#tSys1tempSys", "start": "tSys1", "end": "tempSys", "reltype": "..>", "reltxt": "instance of", "path": "./", "filename": "tempSysInstances.puml"},
 {"id": "REL#tSys2tempSys", "start": "tSys2", "end": "tempSys", "reltype": "..>", "reltxt": "instance of", "path": "./", "filename": "tempSysInstances.puml"},
 {"id": "tempSensorBdCRel#1", "start": "tempSensorBdC", "end": "tempSensorB", "reltype": "..>", "reltxt": "use", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"},
 {"id": "tempSensorBdCRel#2", "start": "tempSensorBdC", "end": "tempConverter", "reltype": "..>", "reltxt": "use", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"}]}

!$allconnections = {"modelconnectionrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples", "modelconnectionrepofile": "./modelrepo_json.puml", "connections": [{"id": "C#2", "start": "temp_dC_tempConverter", "end": "temp_dC_tempSensorBdC", "contype": "--", "contxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"},
 {"id": "C#3", "start": "temp_dF_tempSensorB", "end": "temp_dF_tempConverter", "contype": "--", "contxt": "", "path": "./tempSensorBdC/", "filename": "tempSensorBdC.puml"}]}

