@startuml

package "cmd_utils.py" as pd <<Python>> <<module>> {

    class cmd_utils <<Python>> <<module functions>>{
    +vosda()
    +as()
    }

    class huh <<Python>> <<class>> {
        +__init__(self, hu)
        +hu()

    }

}



@enduml