@startuml
!include modelrepo_json.puml
!include ./../../pumla_macros.puml
!$PUMVarShowDescr = %false()
!$PUMVarShowTaggedValues = %true()
!$PUMVarShowInstantiationRel = %true()

title nice diagram

'PUMLASetElementFilterInTagValue("Vendor", "C Ltd.")

'PUMLAPutAllElementsWithTagValue("Vendor", "C Ltd.")

'PUMLAPutAllElementsWithTagValue("Vendor", "B Inc.")

PUMLAPutAllElements()


@enduml
