!$allrelations = {"modelrelationrepofile": "./relationsrepo_json.puml", "modelrelationrepopath": "/Users/mvoss/Desktop/git/github/pumla/test/examples", "relations": [{"end": "tempSensorB", "reltype": "..>", "filename": "tempSensorBdC.puml", "start": "tempSensorBdC", "reltxt": "use", "path": "./tempSensorBdC/", "id": "R#1"}]}
