'PUMLAMR
@startuml
!include pumla_macros.puml

PUMLAReUsableClass("MyNewClass1", "<<Python>>")
{
    +sayHelloToTheWorld()
}

note as tn1231
hello World!
end note

PUMLARUADescr(tn1231)

PUMLAReUsableAssetFinalize()
@enduml
