'PUMLAMR
@startuml
!include pumla_macros.puml

PUMLAReUsableAsset("Temperature System", tempSys, node, "<<block>>") {

        PUMLARUAPutTaggedValues()

        !if ($PUMVarShowBodyInternals)
        PUMLARUAInternals() {
            PUMLAInjectChildElements(tempSys)
        }
        !endif
}

PUMLARUAAddTaggedValue("Vendor", "C Ltd.")

PUMLARUAInterface("internet", internet_tempSys, "inout")

note as ndescr_tempSys
    a temperature measurement and
    displaying system
end note

PUMLARUADescr(ndescr_tempSys)

PUMLAReUsableAssetFinalize()
@enduml