'PUMLAMR
@startuml
!include ./../../pumla.puml

!if ($PUMVarShowBody)
node "Temperature System" as tempSys {

!if ($PUMVarShowBodyInternals)
PUMLAElementsForScope(tempSys)
!endif

}
!endif

!if ($PUMVarShowDescr)
note bottom of tempSys
    a temperature measurement and
    displaying system
end note
!endif
@enduml