'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../../../pumla_macros.puml
!include ./../modelrepo_json.puml
!include ./../../../pumla_tagged_values.puml


PUMLAReUsableAsset("Temperature Sensor A", tempSensorA, component, "<<block>>") {
    PUMLAPutTaggedValues(tempSensorA)

    PUMLAReUsableAssetInternals() {

        component getSignal
        component "AD conversion"
        component "signal processing"

        PUMLAPutInternalDynElement(internalSequence)
    }
}

PUMLARUAAddTaggedValue("Vendor", "A GmbH")

PUMLAPutInterface("temp_dC", temp_dC_tempSensorA, tempSensorA, "out")

note as tn27
    Temperature Sensor of company A.
    Provides the temperature in degree
    Celsius.
end note

PUMLAReUsableAssetDescr(tn27)

PUMLAReUsableAssetFinalize()

@enduml