'PUMLAMR
'PUMLAPARENT: tempSys
@startuml
!include ./../../../pumla_macros.puml

!if ($PUMVarShowBody)
'add block definition with internals here, e.g.:
component "Temperature Sensor A" <<block>> as tempSensorA {
    !if ($PUMVarShowBodyInternals)

    [getSignal]
    [AD conversion]
    [signal processing]

    !endif
}
!endif

!if ($PUMVarShowInterfaces)
interface "temp_dC" as temp_dC_tempSensorA
temp_dC_tempSensorA <-- tempSensorA
!endif

!if ($PUMVarShowDescr)
note bottom of tempSensorA
    Temperature Sensor of company A.
    Provides the temperatur in degree
    Celsius.
end note

!endif
@enduml