'PUMLAMR
@startuml
!include ./../../../pumla_macros.puml
!include ./../../../pumla_tagged_values.puml
!include ./../modelrepo_json.puml

!if ($PUMVarShowBody)

rectangle "Wireless Unit" <<block>> <<external System>>  as wirelessUnit {

    PUMLAPutTaggedValues(wirelessUnit)

    !if ($PUMVarShowBodyInternals)
    [transmitter]
    [receiver]
    !endif

}
!endif

PUMLAAddTaggedValue(wirelessUnit, "Vendor", "XY")
PUMLAAddTaggedValue(wirelessUnit, "SecurityClass", "Alpha")
PUMLAAddTaggedValue(wirelessUnit, "Frequency Range", "5 GHz")

PUMLAInterface("internet", internet_wirelessUnit, wirelessUnit, "inout")

!if ($PUMVarShowDescr)

note bottom of wirelessUnit
    provide a wireless connection
    to the internet.
end note

!endif

@enduml