'PUMLAMR
@startuml
!include ./../../../pumla_macros.puml
!include ./../../../pumla_tagged_values.puml
!include ./../modelrepo_json.puml

PUMLAReUsableAsset("Wireless Unit", wirelessUnit, rectangle, "<<block>> <<external System>>") {

    PUMLARUAPutTaggedValues()

    !if ($PUMVarShowBodyInternals)
    PUMLARUAInternals() {
        component transmitter
        component receiver
    }
    !endif
}

PUMLARUAAddTaggedValue("Vendor", "XY")
PUMLARUAAddTaggedValue("SecurityClass", "Alpha")
PUMLARUAAddTaggedValue("Frequency Range", "5 GHz")

PUMLARUAInterface("internet", internet_wirelessUnit, "inout")

note as ndescr_wirelessUnit
    provide a wireless connection
    to the internet.
end note

PUMLARUADescr(ndescr_wirelessUnit)

PUMLAReUsableAssetFinalize()
@enduml